- package-lock.json
- package.json
- src/App.tsx
- src/pages/Unauthorized.tsx
- src/pages/error.tsx
- src/pages/index.tsx
- src/pages/login.tsx
- src/utils/router.tsx
권한 없음 message 출력했습니다.
https://github.com/JANGJEEYEON/meet_FE/assets/106160603/8b3042a2-bea5-4adf-91dc-8b057bb57723
> Feat/#21: 권한 에러 페이지 디자인

- src/pages/MeetDetail.tsx
- src/pages/index.tsx
- src/utils/router.tsx
> Feat: 모임 detail 페이지 개발

- src/App.css
- src/pages/MeetDetail.tsx
> feat : 모임 detail 페이지 수정

- src/App.css
- src/pages/MeetList.tsx
- src/pages/index.tsx
- src/utils/router.tsx
모임 component에 제목, 날짜, 장소 보이도록 했습니다.
> feat : 모임 게시판(list) 페이지 개발

- src/App.css
- src/pages/dashboard.tsx
메인 페이지 개발 했습니다.
디자인을 수정해보았고, 사용자가 관리자 일때만, 관리자 버튼이 생겨나도록 해주었습니다. 
하단 네비게이션바 만들어주었고 별도의 연결되는 페이지를 추가할 예정입니다.
> feat:메인페이지 개발

- README.md
> doc : Update README.md

- src/components/PlaceVoteAfter.tsx
- src/components/PlaceVoteBefore.tsx
- src/pages/PlaceVotePage.tsx
- src/pages/index.tsx
- src/types/Meet.ts
- src/types/PlaceVote.ts
- src/utils/router.tsx
장소 투표 페이지 수정했습니다.
https://github.com/user-attachments/assets/e6136c79-2f1a-44c3-92e9-96e5dd4ac646
close #24
> feat : 장소 투표 페이지 개발

- src/components/FooterNav.tsx
- src/pages/MeetList.tsx
- 모임 게시판(list) 전체 조회 -> 리뷰 기반으로 공통 api 형태로 수정 
- 페이지 네이션 기능 추가로 넘어가면서 확인 가능 -> 페이지 네이션 제거 후 스크롤로 변경 
- 각 탭을 누르면 pathvariable 잘 받아와서 상세 페이지로 넘어갈 수 있도록 구현 완료
- FooterNav 생성 후 공통적으로 사용할 수 있도록 수정
https://github.com/user-attachments/assets/3ee7fa35-5653-4afa-9ce3-d4a5498d2d39
> feat: 모임 게시판(list) 기능 개발

- src/pages/admin.tsx
- src/pages/login.tsx
api 호출 함수 server로 모두 변경했습니다.
close #36
> feat : api 호출 동작 통일

- src/components/PlaceVoteBefore.tsx
- src/components/ScheduleVoteBefore.tsx
프론트 배포하면서 필요없는 코드 삭제했습니다.
close #16
> fix: 프로덕션 빌드를 위한 코드 수정

- src/pages/MeetEdit.tsx
- src/pages/index.tsx
- src/utils/router.tsx
모임 수정 페이지 개발했습니다
meetId가 1일 때로 테스트했습니다
https://github.com/user-attachments/assets/4db98fe0-806a-47df-b0bd-af52ef4ac860
close #62
> feat : 모임 수정 페이지 개발

- src/pages/MeetDetail.tsx
- 컨벤션 참고 에러시 에러 페이지로 이동하기로 공통 api 수정 완료 (delete, get)
- issue #31에 해당하는 파일 재 PR 
- 공통 디자인 적용 하지 않음 -> 디자인 통일 완료
- pathvariable 잘 받아옴 meetId
- 임의로 수정, 삭제 나오게끔 했을 때 예시 화면
> feat: 모임 detail 기능 개발

- src/pages/MeetDetail.tsx
- isAuthor == true 수정 
ex) 베이스 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.
> fix: isAuthor 수정

- src/pages/JoinVotePage.tsx
- src/pages/MeetDetail.tsx
- src/pages/MeetEdit.tsx
- src/pages/MeetList.tsx
- src/pages/VotePage.tsx
- src/utils/router.tsx
- 시간 추가
- url에서 meetId를 useParams를 사용하도록 변경
로컬 테스트 완료
> feat : 시간 기능 추가

- src/components/ScheduleVoteAfter.tsx
- src/components/ScheduleVoteBefore.tsx
- src/types/ScheduleVote.ts
일정 투표할 때 시간도 함께 투표하도록 변경했습니다.
https://github.com/user-attachments/assets/d7bf8581-0f61-4692-834e-1cec1f4aeeee
close #79
> feat : 시간 투표 기능 추가

- src/components/JoinVoteAfter.tsx
- src/components/PlaceVoteAfter.tsx
- src/components/ScheduleVoteAfter.tsx
- src/components/popUp/VotedMemberList.tsx
- src/pages/JoinVotePage.tsx
- src/pages/MeetEdit.tsx
- src/pages/VotePage.tsx
- 투표 후 투표한 멤버를 볼수 있는 팝업 개발
- 투표 페이지에 수정/삭제 버튼 추가
- 모임 수정 input에 커서 오른쪽으로 이동
https://github.com/user-attachments/assets/cd3b96ec-4dd3-4437-a787-88b08c9181d7
참여여부 페이지 동일
> 투표 페이지 기능 추가

- src/pages/JoinVotePage.tsx
- src/pages/MeetDetail.tsx
- src/pages/VotePage.tsx
- src/types/Meet.ts
- src/types/participationInfo.ts
- 모임 상세 페이지 접속시 무한 re-rendering 되는 오류 수정
- 타입 추가
로컬 테스 완료
ex) 모임 정보, 날짜 투표 정보 등
Close #31
> fix : 모임 상세 페이지 무한 리렌더링 오류 수정

- src/pages/JoinVotePage.tsx
- src/pages/MeetList.tsx
- src/types/participationInfo.ts
> fix : 시간 오류 해결

- src/pages/MeetDetail.tsx
endDate 비교시 Date 생성자가 자동으로 09시를 추가하는 오류 수정
패딩을 추가하여 스크롤 가능하게 수정
> fix : 날짜 검증 오류 수정

- .gitignore
- src/utils/axios.ts
개발계 서버 url 변경
**.env 서버에 올리면 안됨!!!!**
로컬테스트 완
> feat : 개발계 host 정보 분리
